// emoji_list.js — Erweiterte Emoji-Datenbank mit ~300 Emojis
// Format: Array von { emoji, keywords: [] }

const EMOJI_DATA = [

  // ── Smileys & Gefühle ────────────────────────────────────────────────
  { emoji: '😀', keywords: ['lachen', 'grinsen', 'fröhlich', 'happy', 'smile', 'grin', 'freude'] },
  { emoji: '😂', keywords: ['lachen', 'lustig', 'haha', 'tränen', 'joy', 'funny', 'witzig', 'comedy'] },
  { emoji: '🤣', keywords: ['lachen', 'rollend', 'floor', 'rofl', 'sehr lustig', 'bauchschmerzen'] },
  { emoji: '😊', keywords: ['lächeln', 'süß', 'nett', 'schüchtern', 'smile', 'blush', 'glücklich'] },
  { emoji: '😍', keywords: ['verliebt', 'herzen', 'liebe', 'augen', 'love', 'heart eyes', 'schwärmen'] },
  { emoji: '🥰', keywords: ['verliebt', 'liebe', 'herz', 'zuneigung', 'love', 'cute', 'schatz'] },
  { emoji: '😘', keywords: ['kuss', 'küssen', 'liebe', 'kiss', 'muah', 'bussi', 'herz'] },
  { emoji: '😎', keywords: ['cool', 'sonnenbrille', 'lässig', 'sunglasses', 'swag', 'chillen'] },
  { emoji: '🤩', keywords: ['begeistert', 'star', 'augen', 'wow', 'amazing', 'strahlen', 'aufgeregt'] },
  { emoji: '🥳', keywords: ['party', 'feiern', 'geburtstag', 'celebrate', 'birthday', 'hut'] },
  { emoji: '😤', keywords: ['wütend', 'dampf', 'ärgerlich', 'frustriert', 'angry', 'mad'] },
  { emoji: '😡', keywords: ['wütend', 'sauer', 'ärger', 'rot', 'angry', 'rage', 'zorn'] },
  { emoji: '😭', keywords: ['weinen', 'traurig', 'cry', 'sad', 'tränen', 'schluchzen', 'herzschmerz'] },
  { emoji: '😢', keywords: ['weinen', 'traurig', 'einzelne träne', 'sad', 'cry', 'schmerz'] },
  { emoji: '😔', keywords: ['traurig', 'nachdenklich', 'pensive', 'niedergeschlagen', 'sad'] },
  { emoji: '😟', keywords: ['besorgt', 'traurig', 'worried', 'concerned', 'unruhig'] },
  { emoji: '😰', keywords: ['schwitzen', 'angst', 'kalt', 'sweat', 'anxiety', 'nervös'] },
  { emoji: '😱', keywords: ['schreien', 'schock', 'angst', 'scream', 'shocked', 'entsetzen'] },
  { emoji: '😴', keywords: ['schlafen', 'müde', 'sleep', 'tired', 'zzz', 'schnarchen', 'nap'] },
  { emoji: '🤔', keywords: ['nachdenken', 'denken', 'think', 'hmm', 'überlegen', 'grübeln'] },
  { emoji: '🤗', keywords: ['umarmen', 'hugging', 'hug', 'umarmung', 'liebe', 'warm'] },
  { emoji: '🤭', keywords: ['kicher', 'hand mund', 'oops', 'giggle', 'ups', 'lachen'] },
  { emoji: '🤫', keywords: ['still', 'pst', 'shh', 'geheim', 'quiet', 'shhh', 'leise'] },
  { emoji: '🙄', keywords: ['augen verdrehen', 'genervt', 'eye roll', 'annoyed', 'ugh'] },
  { emoji: '😏', keywords: ['smirk', 'wissend', 'grinsen', 'knowing', 'spöttisch', 'clever'] },
  { emoji: '😬', keywords: ['grimasse', 'peinlich', 'awkward', 'grimace', 'unangenehm'] },
  { emoji: '🥺', keywords: ['bitte', 'please', 'niedlich', 'cute', 'augen', 'puppy eyes', 'flehen'] },
  { emoji: '😒', keywords: ['genervt', 'egal', 'unamused', 'meh', 'langweilig'] },
  { emoji: '😌', keywords: ['erleichtert', 'relieved', 'ruhig', 'entspannt', 'zufrieden'] },
  { emoji: '😷', keywords: ['krank', 'maske', 'mask', 'sick', 'corona', 'erkältet', 'arzt'] },
  { emoji: '🤒', keywords: ['fieber', 'krank', 'fever', 'sick', 'thermometer', 'erkrankt'] },
  { emoji: '🤮', keywords: ['erbrechen', 'kotzen', 'ekelhaft', 'gross', 'sick', 'vomit'] },
  { emoji: '🤡', keywords: ['clown', 'joker', 'zirkus', 'witzig', 'funny', 'creepy'] },
  { emoji: '👻', keywords: ['geist', 'ghost', 'halloween', 'gruselig', 'spooky', 'buh'] },
  { emoji: '💀', keywords: ['tot', 'schädel', 'skull', 'death', 'halloween', 'bones', 'horror'] },
  { emoji: '🤖', keywords: ['roboter', 'robot', 'ki', 'ai', 'maschine', 'tech', 'bot'] },
  { emoji: '👽', keywords: ['alien', 'außerirdisch', 'ufo', 'space', 'extraterrestrial'] },
  { emoji: '😈', keywords: ['teufel', 'böse', 'devil', 'evil', 'böse absichten', 'grinsen'] },
  { emoji: '🥵', keywords: ['heiß', 'hot', 'schwitzen', 'hitze', 'sommer', 'sweat'] },
  { emoji: '🥶', keywords: ['kalt', 'cold', 'frieren', 'eis', 'winter', 'gefroren'] },
  { emoji: '🤑', keywords: ['geld', 'money', 'reich', 'dollar', 'gierig', 'cash'] },

  // ── Gesten & Hände ────────────────────────────────────────────────────
  { emoji: '👍', keywords: ['daumen hoch', 'gut', 'ok', 'thumbs up', 'like', 'super', 'prima'] },
  { emoji: '👎', keywords: ['daumen runter', 'schlecht', 'thumbs down', 'dislike', 'nein', 'nope'] },
  { emoji: '👋', keywords: ['winken', 'hallo', 'tschüss', 'wave', 'hi', 'bye', 'ciao'] },
  { emoji: '🤝', keywords: ['handschlag', 'deal', 'einigung', 'handshake', 'agreement', 'partner'] },
  { emoji: '👏', keywords: ['klatschen', 'applaus', 'clap', 'bravo', 'gut gemacht', 'wow'] },
  { emoji: '🙏', keywords: ['bitte', 'danke', 'pray', 'beten', 'please', 'hands', 'thank you'] },
  { emoji: '✌️', keywords: ['frieden', 'peace', 'victory', 'zwei', 'v', 'sieg'] },
  { emoji: '🤞', keywords: ['daumen drücken', 'glück', 'fingers crossed', 'lucky', 'hoffnung'] },
  { emoji: '🤙', keywords: ['hang loose', 'ruf an', 'call me', 'surfer', 'entspannt'] },
  { emoji: '💪', keywords: ['muskel', 'stark', 'muscle', 'strong', 'power', 'bicep', 'training'] },
  { emoji: '👊', keywords: ['faust', 'schlag', 'punch', 'fistbump', 'kampf'] },
  { emoji: '✋', keywords: ['stop', 'hand', 'halt', 'high five', 'stopp'] },
  { emoji: '🖐️', keywords: ['hand', 'fünf', 'hi5', 'five', 'high five'] },
  { emoji: '👆', keywords: ['zeigen', 'oben', 'up', 'pointer', 'point up'] },
  { emoji: '👇', keywords: ['zeigen', 'unten', 'down', 'pointer', 'point down'] },
  { emoji: '👉', keywords: ['zeigen', 'rechts', 'right', 'pointer', 'hier'] },
  { emoji: '👈', keywords: ['zeigen', 'links', 'left', 'pointer', 'dort'] },
  { emoji: '🖕', keywords: ['mittelfinger', 'flip off', 'finger', 'beleidigung', 'fuck'] },

  // ── Herzen & Liebe ────────────────────────────────────────────────────
  { emoji: '❤️', keywords: ['herz', 'liebe', 'heart', 'love', 'rot', 'romantik'] },
  { emoji: '🧡', keywords: ['herz', 'orange', 'heart', 'liebe', 'wärme'] },
  { emoji: '💛', keywords: ['herz', 'gelb', 'heart', 'liebe', 'freundschaft', 'yellow'] },
  { emoji: '💚', keywords: ['herz', 'grün', 'heart', 'natur', 'green', 'gesundheit'] },
  { emoji: '💙', keywords: ['herz', 'blau', 'heart', 'blue', 'trauer', 'liebe'] },
  { emoji: '💜', keywords: ['herz', 'lila', 'heart', 'purple', 'romantik', 'magie'] },
  { emoji: '🖤', keywords: ['herz', 'schwarz', 'black heart', 'dunkel', 'gothic'] },
  { emoji: '🤍', keywords: ['herz', 'weiß', 'white heart', 'reinheit', 'clean'] },
  { emoji: '💔', keywords: ['gebrochenes herz', 'herzschmerz', 'breakup', 'break up', 'trennung', 'sad'] },
  { emoji: '💕', keywords: ['zwei herzen', 'liebe', 'romantik', 'hearts', 'couple', 'paar'] },
  { emoji: '💖', keywords: ['funkelndes herz', 'liebe', 'sparkling heart', 'romantik'] },
  { emoji: '💗', keywords: ['wachsendes herz', 'liebe', 'growing heart', 'pink'] },
  { emoji: '💘', keywords: ['herz pfeil', 'verliebt', 'amor', 'cupid', 'heart arrow'] },

  // ── Tiere ─────────────────────────────────────────────────────────────
  { emoji: '🐶', keywords: ['hund', 'dog', 'welpe', 'haustier', 'puppy', 'wau'] },
  { emoji: '🐱', keywords: ['katze', 'cat', 'kitty', 'kätzchen', 'haustier', 'miau'] },
  { emoji: '🐰', keywords: ['hase', 'rabbit', 'kaninchen', 'ostern', 'bunny'] },
  { emoji: '🐹', keywords: ['hamster', 'niedlich', 'nager', 'hamster', 'cute'] },
  { emoji: '🦊', keywords: ['fuchs', 'fox', 'schlau', 'orange', 'clever'] },
  { emoji: '🐻', keywords: ['bär', 'bear', 'teddy', 'braun', 'grizzly'] },
  { emoji: '🐼', keywords: ['panda', 'china', 'niedlich', 'schwarz weiß', 'cute'] },
  { emoji: '🐨', keywords: ['koala', 'australien', 'beutel', 'niedlich', 'cute'] },
  { emoji: '🐯', keywords: ['tiger', 'gestreift', 'wild', 'gefährlich', 'cat'] },
  { emoji: '🦁', keywords: ['löwe', 'lion', 'könig', 'wild', 'mähne', 'africa'] },
  { emoji: '🐮', keywords: ['kuh', 'cow', 'bauernhof', 'milch', 'muh', 'farm'] },
  { emoji: '🐷', keywords: ['schwein', 'pig', 'oink', 'bauernhof', 'rüssel', 'farm'] },
  { emoji: '🐸', keywords: ['frosch', 'frog', 'grün', 'teich', 'kröte', 'spring'] },
  { emoji: '🐵', keywords: ['affe', 'monkey', 'lustig', 'dschungel', 'jungle'] },
  { emoji: '🐔', keywords: ['huhn', 'chicken', 'henne', 'bauernhof', 'ei', 'gak'] },
  { emoji: '🐧', keywords: ['pinguin', 'penguin', 'eis', 'polar', 'schwarz weiß'] },
  { emoji: '🐦', keywords: ['vogel', 'bird', 'fliegen', 'natur', 'tweet'] },
  { emoji: '🦅', keywords: ['adler', 'eagle', 'stolz', 'stark', 'usa', 'fliegen'] },
  { emoji: '🦆', keywords: ['ente', 'duck', 'wasser', 'quak', 'teich'] },
  { emoji: '🦋', keywords: ['schmetterling', 'butterfly', 'schön', 'natur', 'frühling'] },
  { emoji: '🐝', keywords: ['biene', 'bee', 'honig', 'stechen', 'summen', 'honey'] },
  { emoji: '🐛', keywords: ['raupe', 'caterpillar', 'wurm', 'grün', 'schmetterling'] },
  { emoji: '🦎', keywords: ['eidechse', 'lizard', 'reptil', 'grün', 'gecko'] },
  { emoji: '🐍', keywords: ['schlange', 'snake', 'reptil', 'giftig', 'zischen'] },
  { emoji: '🐢', keywords: ['schildkröte', 'turtle', 'langsam', 'meer', 'slow'] },
  { emoji: '🦈', keywords: ['hai', 'shark', 'meer', 'gefährlich', 'fisch', 'ocean'] },
  { emoji: '🐬', keywords: ['delfin', 'dolphin', 'meer', 'intelligent', 'springen'] },
  { emoji: '🐋', keywords: ['wal', 'whale', 'meer', 'groß', 'ozean', 'blau'] },
  { emoji: '🦁', keywords: ['löwe', 'lion', 'wild', 'könig', 'africa', 'mähne'] },
  { emoji: '🐘', keywords: ['elefant', 'elephant', 'groß', 'rüssel', 'africa', 'memory'] },
  { emoji: '🦒', keywords: ['giraffe', 'giraffe', 'hals', 'africa', 'lang', 'spotted'] },
  { emoji: '🦓', keywords: ['zebra', 'zebra', 'streifen', 'africa', 'gestreift'] },
  { emoji: '🦏', keywords: ['nashorn', 'rhino', 'horn', 'africa', 'gefährlich'] },
  { emoji: '🦘', keywords: ['känguru', 'kangaroo', 'australien', 'beutel', 'springen'] },

  // ── Essen & Trinken ───────────────────────────────────────────────────
  { emoji: '🍕', keywords: ['pizza', 'essen', 'italien', 'käse', 'food', 'lecker'] },
  { emoji: '🍔', keywords: ['burger', 'hamburger', 'fast food', 'essen', 'food'] },
  { emoji: '🌮', keywords: ['taco', 'mexiko', 'mexican', 'essen', 'food'] },
  { emoji: '🌯', keywords: ['wrap', 'burrito', 'mexiko', 'essen', 'food'] },
  { emoji: '🍜', keywords: ['nudeln', 'ramen', 'asiatisch', 'essen', 'noodles', 'japan'] },
  { emoji: '🍣', keywords: ['sushi', 'japan', 'fisch', 'essen', 'asiatisch', 'reis'] },
  { emoji: '🍦', keywords: ['eis', 'ice cream', 'soft serve', 'sommer', 'süß'] },
  { emoji: '🍰', keywords: ['kuchen', 'cake', 'geburtstag', 'torte', 'süß', 'dessert'] },
  { emoji: '🎂', keywords: ['geburtstagskuchen', 'birthday cake', 'kerzen', 'geburtstag'] },
  { emoji: '🍩', keywords: ['donut', 'doughnut', 'süß', 'dessert', 'lecker'] },
  { emoji: '🍫', keywords: ['schokolade', 'chocolate', 'süß', 'braun', 'lecker'] },
  { emoji: '🍬', keywords: ['bonbon', 'candy', 'süßigkeit', 'zucker', 'sweet'] },
  { emoji: '🍭', keywords: ['lolli', 'lollipop', 'süß', 'candy', 'farbe'] },
  { emoji: '☕', keywords: ['kaffee', 'coffee', 'morgen', 'heißgetränk', 'espresso', 'cafe'] },
  { emoji: '🍵', keywords: ['tee', 'tea', 'heißgetränk', 'grüner tee', 'matcha'] },
  { emoji: '🧃', keywords: ['saft', 'juice', 'trinken', 'obst', 'box', 'fruchtsaft'] },
  { emoji: '🥤', keywords: ['limonade', 'soft drink', 'strohhalm', 'cola', 'soda'] },
  { emoji: '🍺', keywords: ['bier', 'beer', 'alkohol', 'prost', 'cheers', 'glas'] },
  { emoji: '🍻', keywords: ['bierkrüge', 'prost', 'cheers', 'beer', 'trinken', 'anstoßen'] },
  { emoji: '🥂', keywords: ['sekt', 'champagner', 'prost', 'champagne', 'feiern', 'celebration'] },
  { emoji: '🍷', keywords: ['wein', 'wine', 'rot', 'alkohol', 'elegant', 'abend'] },
  { emoji: '🍎', keywords: ['apfel', 'apple', 'rot', 'obst', 'fruit', 'gesund'] },
  { emoji: '🍊', keywords: ['orange', 'frucht', 'citrus', 'obst', 'saft', 'fruit'] },
  { emoji: '🍋', keywords: ['zitrone', 'lemon', 'gelb', 'sauer', 'citrus', 'fruit'] },
  { emoji: '🍇', keywords: ['trauben', 'grapes', 'wein', 'obst', 'lila', 'fruit'] },
  { emoji: '🍓', keywords: ['erdbeere', 'strawberry', 'rot', 'obst', 'sommer', 'fruit'] },
  { emoji: '🍉', keywords: ['wassermelone', 'watermelon', 'sommer', 'rot', 'grün', 'fruit'] },
  { emoji: '🥑', keywords: ['avocado', 'gesund', 'grün', 'hipster', 'toast', 'food'] },
  { emoji: '🌽', keywords: ['mais', 'corn', 'gelb', 'sommer', 'grillen', 'food'] },
  { emoji: '🥕', keywords: ['karotte', 'carrot', 'orange', 'gesund', 'hase', 'gemüse'] },
  { emoji: '🥦', keywords: ['brokkoli', 'broccoli', 'grün', 'gesund', 'gemüse'] },

  // ── Natur & Wetter ────────────────────────────────────────────────────
  { emoji: '☀️', keywords: ['sonne', 'sun', 'schön', 'warm', 'sommer', 'strahlend', 'hell'] },
  { emoji: '🌙', keywords: ['mond', 'moon', 'nacht', 'night', 'schlaf', 'dunkel'] },
  { emoji: '⭐', keywords: ['stern', 'star', 'gut', 'leistung', 'bewertung', 'rating'] },
  { emoji: '🌟', keywords: ['glitzer stern', 'star', 'besonders', 'glänzend', 'toll'] },
  { emoji: '✨', keywords: ['glitzer', 'sparkle', 'magie', 'magic', 'glänzend', 'neu'] },
  { emoji: '🌈', keywords: ['regenbogen', 'rainbow', 'farben', 'schön', 'hoffnung', 'bunt'] },
  { emoji: '☁️', keywords: ['wolke', 'cloud', 'grau', 'bedeckt', 'regen'] },
  { emoji: '⛅', keywords: ['teils bewölkt', 'sonne wolken', 'partly cloudy'] },
  { emoji: '🌧️', keywords: ['regen', 'rain', 'nass', 'grau', 'traurig', 'weather'] },
  { emoji: '⛈️', keywords: ['gewitter', 'storm', 'blitz', 'thunder', 'donner', 'regen'] },
  { emoji: '❄️', keywords: ['schnee', 'snow', 'kalt', 'winter', 'eis', 'flocke'] },
  { emoji: '🌊', keywords: ['welle', 'wave', 'meer', 'ocean', 'surfen', 'wasser'] },
  { emoji: '🌍', keywords: ['erde', 'erde europa', 'earth', 'welt', 'global', 'planet'] },
  { emoji: '🌎', keywords: ['erde', 'erde americas', 'earth', 'welt', 'global'] },
  { emoji: '🌏', keywords: ['erde', 'erde asien', 'earth', 'welt', 'global', 'asien'] },
  { emoji: '🏔️', keywords: ['berg', 'mountain', 'schnee', 'alpen', 'wandern', 'hoch'] },
  { emoji: '🌋', keywords: ['vulkan', 'volcano', 'ausbruch', 'feuer', 'lava'] },
  { emoji: '🏝️', keywords: ['insel', 'island', 'strand', 'palme', 'urlaub', 'vacation'] },
  { emoji: '🌴', keywords: ['palme', 'palm tree', 'sommer', 'urlaub', 'strand', 'tropical'] },
  { emoji: '🌵', keywords: ['kaktus', 'cactus', 'wüste', 'desert', 'dürr', 'mexico'] },
  { emoji: '🌸', keywords: ['kirschblüte', 'blüte', 'japan', 'frühling', 'rosa', 'cherry blossom'] },
  { emoji: '🌺', keywords: ['blume', 'flower', 'rot', 'hawaii', 'hibiskus', 'tropisch'] },
  { emoji: '🌻', keywords: ['sonnenblume', 'sunflower', 'gelb', 'sommer', 'feld'] },
  { emoji: '🌹', keywords: ['rose', 'rot', 'liebe', 'romantik', 'flower', 'blume'] },
  { emoji: '🍀', keywords: ['kleeblatt', 'glück', 'vier blätter', 'lucky', 'irland', 'shamrock'] },
  { emoji: '🍁', keywords: ['ahornblatt', 'maple', 'herbst', 'fall', 'kanada', 'rot'] },
  { emoji: '🐚', keywords: ['muschel', 'shell', 'meer', 'strand', 'ocean', 'beach'] },

  // ── Objekte & Symbole ─────────────────────────────────────────────────
  { emoji: '🔥', keywords: ['feuer', 'fire', 'heiß', 'hot', 'lit', 'geil', 'krass', 'trending'] },
  { emoji: '💧', keywords: ['wasser', 'tropfen', 'water', 'drop', 'nass', 'regen'] },
  { emoji: '💡', keywords: ['glühbirne', 'idee', 'idea', 'licht', 'light', 'einfall'] },
  { emoji: '🔑', keywords: ['schlüssel', 'key', 'tür', 'wichtig', 'geheim', 'öffnen'] },
  { emoji: '🔒', keywords: ['schloss', 'lock', 'sicher', 'verschlossen', 'privat', 'secure'] },
  { emoji: '🔓', keywords: ['geöffnet', 'unlock', 'offen', 'frei', 'open'] },
  { emoji: '📱', keywords: ['handy', 'smartphone', 'mobile', 'telefon', 'phone', 'iphone'] },
  { emoji: '💻', keywords: ['laptop', 'computer', 'notebook', 'pc', 'arbeiten', 'tech'] },
  { emoji: '🖥️', keywords: ['monitor', 'computer', 'desktop', 'bildschirm', 'screen'] },
  { emoji: '⌨️', keywords: ['tastatur', 'keyboard', 'tippen', 'schreiben', 'eingabe'] },
  { emoji: '🖱️', keywords: ['maus', 'mouse', 'klicken', 'click', 'computer'] },
  { emoji: '🎮', keywords: ['gamepad', 'gaming', 'spielen', 'game', 'controller', 'zocken'] },
  { emoji: '📷', keywords: ['kamera', 'camera', 'foto', 'photo', 'bild', 'fotografieren'] },
  { emoji: '🎵', keywords: ['musik', 'note', 'music', 'song', 'melodie', 'töne'] },
  { emoji: '🎶', keywords: ['musik', 'noten', 'music', 'song', 'melodie', 'hören'] },
  { emoji: '🎧', keywords: ['kopfhörer', 'headphones', 'musik', 'hören', 'audio'] },
  { emoji: '🔊', keywords: ['lautsprecher', 'speaker', 'laut', 'sound', 'audio', 'volume'] },
  { emoji: '🔕', keywords: ['stumm', 'mute', 'stille', 'still', 'silent', 'benachrichtigung aus'] },
  { emoji: '📚', keywords: ['bücher', 'books', 'lesen', 'lernen', 'bibliothek', 'wissen'] },
  { emoji: '📖', keywords: ['buch', 'book', 'lesen', 'öffnen', 'seite', 'roman'] },
  { emoji: '✏️', keywords: ['bleistift', 'pencil', 'schreiben', 'zeichnen', 'edit'] },
  { emoji: '🖊️', keywords: ['stift', 'pen', 'schreiben', 'unterschrift', 'write'] },
  { emoji: '📝', keywords: ['notiz', 'note', 'schreiben', 'memo', 'aufschreiben', 'liste'] },
  { emoji: '📋', keywords: ['klemmbrett', 'clipboard', 'liste', 'aufgaben', 'checkliste'] },
  { emoji: '📌', keywords: ['stecknadel', 'pin', 'markieren', 'wichtig', 'ort', 'location'] },
  { emoji: '📎', keywords: ['büroklammer', 'paperclip', 'anhang', 'attachment', 'verbinden'] },
  { emoji: '✂️', keywords: ['schere', 'scissors', 'schneiden', 'ausschneiden', 'cut'] },
  { emoji: '🗑️', keywords: ['mülleimer', 'trash', 'löschen', 'delete', 'wegwerfen'] },
  { emoji: '💰', keywords: ['geld', 'money', 'reich', 'dollar', 'cash', 'verdienen'] },
  { emoji: '💳', keywords: ['kreditkarte', 'card', 'bezahlen', 'payment', 'bank'] },
  { emoji: '🏆', keywords: ['pokal', 'trophy', 'gewonnen', 'sieger', 'champion', 'win'] },
  { emoji: '🥇', keywords: ['gold', 'erste', 'first', 'gewinner', 'medaille', '1.'] },
  { emoji: '🥈', keywords: ['silber', 'zweite', 'second', 'medaille', '2.'] },
  { emoji: '🥉', keywords: ['bronze', 'dritte', 'third', 'medaille', '3.'] },
  { emoji: '🎯', keywords: ['ziel', 'target', 'treffer', 'bullseye', 'dart', 'fokus'] },
  { emoji: '🎁', keywords: ['geschenk', 'present', 'gift', 'überraschung', 'geburtstag'] },
  { emoji: '🎉', keywords: ['party', 'konfetti', 'feiern', 'celebrate', 'tada', 'hurra'] },
  { emoji: '🎊', keywords: ['konfetti', 'feiern', 'party', 'celebrate', 'feier'] },
  { emoji: '🚀', keywords: ['rakete', 'rocket', 'start', 'launch', 'schnell', 'space', 'aufstieg'] },
  { emoji: '⚡', keywords: ['blitz', 'lightning', 'schnell', 'energie', 'energie', 'strom'] },
  { emoji: '💥', keywords: ['explosion', 'boom', 'knall', 'collision', 'wow', 'crash'] },
  { emoji: '✅', keywords: ['check', 'haken', 'done', 'fertig', 'ok', 'erledigt', 'check mark'] },
  { emoji: '❌', keywords: ['x', 'fehler', 'falsch', 'nein', 'no', 'wrong', 'error'] },
  { emoji: '⚠️', keywords: ['warnung', 'warning', 'achtung', 'alert', 'gefahr', 'vorsicht'] },
  { emoji: 'ℹ️', keywords: ['info', 'information', 'hinweis', 'information'] },
  { emoji: '❓', keywords: ['frage', 'question', 'was', 'unklar', 'warum', 'hä'] },
  { emoji: '❗', keywords: ['ausrufezeichen', 'wichtig', 'achtung', 'alarm', 'dringend'] },
  { emoji: '🔍', keywords: ['suche', 'lupe', 'search', 'finden', 'zoom', 'untersuchen'] },
  { emoji: '🏠', keywords: ['haus', 'home', 'zuhause', 'house', 'wohnen', 'gebäude'] },
  { emoji: '🏢', keywords: ['büro', 'gebäude', 'office', 'building', 'firma', 'arbeit'] },
  { emoji: '🏥', keywords: ['krankenhaus', 'hospital', 'arzt', 'medizin', 'notruf'] },
  { emoji: '🏫', keywords: ['schule', 'school', 'lernen', 'bildung', 'klasse'] },
  { emoji: '🏗️', keywords: ['baustelle', 'construction', 'bau', 'kran', 'bauen'] },

  // ── Verkehr & Fahrzeuge ───────────────────────────────────────────────
  { emoji: '🚗', keywords: ['auto', 'car', 'fahren', 'pkw', 'fahrzeug', 'transport'] },
  { emoji: '🚙', keywords: ['suv', 'auto', 'car', 'gelände', 'fahrzeug'] },
  { emoji: '🚕', keywords: ['taxi', 'cab', 'fahren', 'gelb', 'uber'] },
  { emoji: '🚌', keywords: ['bus', 'öpnv', 'nahverkehr', 'transport', 'öffentlich'] },
  { emoji: '🚆', keywords: ['zug', 'train', 'bahn', 'icn', 'reisen', 'schnell'] },
  { emoji: '✈️', keywords: ['flugzeug', 'airplane', 'fliegen', 'reisen', 'urlaub', 'flug'] },
  { emoji: '🚢', keywords: ['schiff', 'ship', 'meer', 'kreuzfahrt', 'reisen', 'boot'] },
  { emoji: '🚲', keywords: ['fahrrad', 'bike', 'cycling', 'sport', 'umwelt', 'rad'] },
  { emoji: '🛵', keywords: ['moped', 'roller', 'scooter', 'lieferando', 'pizza'] },
  { emoji: '🏍️', keywords: ['motorrad', 'motorcycle', 'biker', 'moto', 'fahren'] },
  { emoji: '🚁', keywords: ['hubschrauber', 'helicopter', 'fliegen', 'notruf', 'rettung'] },
  { emoji: '🛸', keywords: ['ufo', 'alien', 'space', 'fliegen', 'science fiction'] },
  { emoji: '⛵', keywords: ['segelboot', 'sailboat', 'meer', 'wind', 'segeln'] },

  // ── Sport ─────────────────────────────────────────────────────────────
  { emoji: '⚽', keywords: ['fußball', 'soccer', 'sport', 'ball', 'tor', 'bundesliga'] },
  { emoji: '🏀', keywords: ['basketball', 'sport', 'ball', 'nba', 'basketball'] },
  { emoji: '🏈', keywords: ['american football', 'nfl', 'sport', 'ball', 'usa'] },
  { emoji: '⚾', keywords: ['baseball', 'sport', 'ball', 'mlb', 'usa'] },
  { emoji: '🎾', keywords: ['tennis', 'sport', 'wimbledon', 'ball', 'schläger'] },
  { emoji: '🏐', keywords: ['volleyball', 'sport', 'ball', 'strand', 'beach'] },
  { emoji: '🏊', keywords: ['schwimmen', 'swimming', 'wasser', 'sport', 'olympia'] },
  { emoji: '🚴', keywords: ['radfahren', 'cycling', 'sport', 'fahrrad', 'tour'] },
  { emoji: '🏋️', keywords: ['gewichtheben', 'fitness', 'gym', 'sport', 'hantel', 'training'] },
  { emoji: '🥊', keywords: ['boxen', 'boxing', 'kampf', 'sport', 'handschuh'] },
  { emoji: '⛷️', keywords: ['skifahren', 'skiing', 'winter', 'sport', 'schnee', 'alpen'] },
  { emoji: '🏂', keywords: ['snowboard', 'winter', 'sport', 'schnee', 'board'] },
  { emoji: '🎿', keywords: ['ski', 'skifahren', 'winter', 'sport', 'schnee'] },
  { emoji: '⛳', keywords: ['golf', 'sport', 'grün', 'loch', 'schläger'] },
  { emoji: '🥋', keywords: ['kampfsport', 'martial arts', 'karate', 'judo', 'sport'] },

  // ── Flaggen ────────────────────────────────────────────────────────────
  { emoji: '🇩🇪', keywords: ['deutschland', 'germany', 'flagge', 'de', 'deutsch', 'german'] },
  { emoji: '🇦🇹', keywords: ['österreich', 'austria', 'flagge', 'at', 'österreichisch'] },
  { emoji: '🇨🇭', keywords: ['schweiz', 'switzerland', 'flagge', 'ch', 'swiss'] },
  { emoji: '🇺🇸', keywords: ['usa', 'vereinigte staaten', 'america', 'flagge', 'us', 'american'] },
  { emoji: '🇬🇧', keywords: ['uk', 'england', 'britain', 'flagge', 'gb', 'british'] },
  { emoji: '🇫🇷', keywords: ['frankreich', 'france', 'flagge', 'fr', 'französisch'] },
  { emoji: '🇮🇹', keywords: ['italien', 'italy', 'flagge', 'it', 'italienisch', 'pizza'] },
  { emoji: '🇪🇸', keywords: ['spanien', 'spain', 'flagge', 'es', 'spanisch'] },
  { emoji: '🇳🇱', keywords: ['niederlande', 'netherlands', 'flagge', 'nl', 'holland'] },
  { emoji: '🇯🇵', keywords: ['japan', 'flagge', 'jp', 'japanisch', 'tokio'] },
  { emoji: '🇨🇳', keywords: ['china', 'flagge', 'cn', 'chinesisch', 'peking'] },
  { emoji: '🇷🇺', keywords: ['russland', 'russia', 'flagge', 'ru', 'russisch'] },
  { emoji: '🇧🇷', keywords: ['brasilien', 'brazil', 'flagge', 'br', 'brasilianisch'] },
  { emoji: '🇨🇦', keywords: ['kanada', 'canada', 'flagge', 'ca', 'kanadisch', 'maple'] },
  { emoji: '🇦🇺', keywords: ['australien', 'australia', 'flagge', 'au', 'australisch'] },
  { emoji: '🏳️‍🌈', keywords: ['regenbogen', 'lgbt', 'pride', 'gay', 'queer', 'flagge'] },

];

module.exports = EMOJI_DATA;
