// acronyms_list.js — Erweiterte Abkürzungsdatenbank mit ~300 Einträgen
// Format: { long, category, description }

const acronyms_data = {

  // ── Behörden & Recht ──────────────────────────────────────────────────
  'DSGVO': { long: 'Datenschutz-Grundverordnung', category: 'Recht', description: 'EU-Datenschutzrecht seit Mai 2018, regelt den Umgang mit personenbezogenen Daten' },
  'BDSG': { long: 'Bundesdatenschutzgesetz', category: 'Recht', description: 'Nationales deutsches Datenschutzgesetz, ergänzt die DSGVO' },
  'StGB': { long: 'Strafgesetzbuch', category: 'Recht', description: 'Wichtigstes Strafgesetz in Deutschland' },
  'StPO': { long: 'Strafprozessordnung', category: 'Recht', description: 'Regelt das Strafverfahren in Deutschland' },
  'StVO': { long: 'Straßenverkehrs-Ordnung', category: 'Recht', description: 'Regelt das Verhalten im Straßenverkehr in Deutschland' },
  'StVG': { long: 'Straßenverkehrsgesetz', category: 'Recht', description: 'Grundgesetz für den Straßenverkehr' },
  'BGB': { long: 'Bürgerliches Gesetzbuch', category: 'Recht', description: 'Zentrales Zivilrecht in Deutschland seit 1900' },
  'ZPO': { long: 'Zivilprozessordnung', category: 'Recht', description: 'Regelt Ablauf von Zivilprozessen vor Gerichten' },
  'GG': { long: 'Grundgesetz', category: 'Recht', description: 'Verfassung der Bundesrepublik Deutschland seit 1949' },
  'VwGO': { long: 'Verwaltungsgerichtsordnung', category: 'Recht', description: 'Regelt Verwaltungsgerichtsverfahren' },
  'HGB': { long: 'Handelsgesetzbuch', category: 'Recht', description: 'Wichtigstes Gesetz für Kaufleute und Handelsrecht' },
  'GmbHG': { long: 'GmbH-Gesetz', category: 'Recht', description: 'Gesetz über Gesellschaften mit beschränkter Haftung' },
  'KWG': { long: 'Kreditwesengesetz', category: 'Recht', description: 'Regelt Banken und Kreditinstitute in Deutschland' },
  'GWB': { long: 'Gesetz gegen Wettbewerbsbeschränkungen', category: 'Recht', description: 'Kartellrecht und Wettbewerbsrecht' },
  'BAFÖG': { long: 'Bundesausbildungsförderungsgesetz', category: 'Recht', description: 'Staatliche Förderung für Schüler und Studenten' },
  'ArbSchG': { long: 'Arbeitsschutzgesetz', category: 'Recht', description: 'Regelt Sicherheit und Gesundheit am Arbeitsplatz' },
  'AGG': { long: 'Allgemeines Gleichbehandlungsgesetz', category: 'Recht', description: 'Verbietet Diskriminierung aufgrund von Rasse, Geschlecht, Religion usw.' },
  'KSchG': { long: 'Kündigungsschutzgesetz', category: 'Recht', description: 'Schützt Arbeitnehmer vor ungerechtfertigter Kündigung' },
  'InsO': { long: 'Insolvenzordnung', category: 'Recht', description: 'Regelt das Insolvenzverfahren in Deutschland' },
  'UrhG': { long: 'Urheberrechtsgesetz', category: 'Recht', description: 'Schützt geistige Werke wie Musik, Text, Bilder' },
  'TKG': { long: 'Telekommunikationsgesetz', category: 'Recht', description: 'Regelt die Telekommunikationsbranche in Deutschland' },
  'TTDSG': { long: 'Telekommunikation-Telemedien-Datenschutz-Gesetz', category: 'Recht', description: 'Novelle: Cookies, Tracking und Datenschutz online' },

  // ── Behörden & Organisationen ──────────────────────────────────────────
  'BKA': { long: 'Bundeskriminalamt', category: 'Behörde', description: 'Zentrale Bundesbehörde für Kriminalitätsbekämpfung in Deutschland' },
  'BND': { long: 'Bundesnachrichtendienst', category: 'Behörde', description: 'Auslandsgeheimdienst der Bundesrepublik Deutschland' },
  'LKA': { long: 'Landeskriminalamt', category: 'Behörde', description: 'Landesbehörde zur Kriminalitätsbekämpfung' },
  'THW': { long: 'Technisches Hilfswerk', category: 'Behörde', description: 'Bundesbehörde für technische Hilfe bei Katastrophen' },
  'BGS': { long: 'Bundesgrenzschutz', category: 'Behörde', description: 'Heute: Bundespolizei, Schutz der Grenzen' },
  'BA': { long: 'Bundesagentur für Arbeit', category: 'Behörde', description: 'Zuständig für Arbeitslosengeld, Jobvermittlung und Ausbildungsförderung' },
  'BaFin': { long: 'Bundesanstalt für Finanzdienstleistungsaufsicht', category: 'Behörde', description: 'Überwacht Banken, Versicherungen und Kapitalmärkte' },
  'BSI': { long: 'Bundesamt für Sicherheit in der Informationstechnik', category: 'Behörde', description: 'Zuständig für IT-Sicherheit in Deutschland' },
  'BMJV': { long: 'Bundesministerium der Justiz und für Verbraucherschutz', category: 'Behörde', description: 'Ministerium für Recht und Verbraucherschutz' },
  'BMF': { long: 'Bundesministerium der Finanzen', category: 'Behörde', description: 'Zuständig für die Haushaltspolitik Deutschlands' },
  'TÜV': { long: 'Technischer Überwachungsverein', category: 'Behörde', description: 'Prüft die Sicherheit von Fahrzeugen und technischen Anlagen' },
  'ADFC': { long: 'Allgemeiner Deutscher Fahrrad-Club', category: 'Organisation', description: 'Interessenverband für Radfahrer in Deutschland' },
  'DRK': { long: 'Deutsches Rotes Kreuz', category: 'Organisation', description: 'Hilfsorganisation für Erste Hilfe und humanitäre Arbeit' },
  'ASB': { long: 'Arbeiter-Samariter-Bund', category: 'Organisation', description: 'Hilfs- und Wohlfahrtsorganisation' },
  'THW': { long: 'Technisches Hilfswerk', category: 'Organisation', description: 'Hilfeleistung bei Katastrophen und Großschadensereignissen' },
  'DGB': { long: 'Deutscher Gewerkschaftsbund', category: 'Organisation', description: 'Dachverband der Gewerkschaften in Deutschland' },

  // ── Technik & IT ──────────────────────────────────────────────────────
  'KI': { long: 'Künstliche Intelligenz', category: 'IT', description: 'Computersysteme, die menschliche Intelligenz simulieren' },
  'AI': { long: 'Artificial Intelligence', category: 'IT', description: 'Englische Bezeichnung für Künstliche Intelligenz' },
  'ML': { long: 'Machine Learning', category: 'IT', description: 'KI-Teilbereich: Computer lernt aus Daten ohne explizite Programmierung' },
  'NFC': { long: 'Near Field Communication', category: 'IT', description: 'Nahfeldkommunikation für kontaktloses Bezahlen und Datenaustausch' },
  'URL': { long: 'Uniform Resource Locator', category: 'IT', description: 'Eindeutige Adresse einer Ressource im Internet (Webadresse)' },
  'HTTP': { long: 'Hypertext Transfer Protocol', category: 'IT', description: 'Protokoll zur Übertragung von Daten im Web' },
  'HTTPS': { long: 'Hypertext Transfer Protocol Secure', category: 'IT', description: 'Verschlüsselte Version von HTTP für sichere Kommunikation' },
  'SSL': { long: 'Secure Sockets Layer', category: 'IT', description: 'Verschlüsselungsprotokoll für sichere Datenübertragung (heute TLS)' },
  'TLS': { long: 'Transport Layer Security', category: 'IT', description: 'Modernes Verschlüsselungsprotokoll, Nachfolger von SSL' },
  'IP': { long: 'Internet Protocol', category: 'IT', description: 'Grundlegendes Protokoll für die Kommunikation im Internet' },
  'DNS': { long: 'Domain Name System', category: 'IT', description: 'Übersetzt Domainnamen in IP-Adressen' },
  'VPN': { long: 'Virtual Private Network', category: 'IT', description: 'Verschlüsselte Verbindung für sichere und anonyme Internetnutzung' },
  'WLAN': { long: 'Wireless Local Area Network', category: 'IT', description: 'Drahtloses Netzwerk (Wi-Fi)' },
  'LAN': { long: 'Local Area Network', category: 'IT', description: 'Lokales Netzwerk über Kabel' },
  'WAN': { long: 'Wide Area Network', category: 'IT', description: 'Weitverkehrsnetz, verbindet LANs über große Entfernungen' },
  'SSD': { long: 'Solid-State-Drive', category: 'IT', description: 'Schneller Flash-Speicher als Festplattenersatz' },
  'HDD': { long: 'Hard Disk Drive', category: 'IT', description: 'Klassische magnetische Festplatte' },
  'RAM': { long: 'Random Access Memory', category: 'IT', description: 'Flüchtiger Arbeitsspeicher eines Computers' },
  'ROM': { long: 'Read-Only Memory', category: 'IT', description: 'Nur-Lese-Speicher, z.B. für Firmware' },
  'CPU': { long: 'Central Processing Unit', category: 'IT', description: 'Hauptprozessor eines Computers – das „Gehirn"' },
  'GPU': { long: 'Graphics Processing Unit', category: 'IT', description: 'Grafikprozessor für Rendering und KI-Berechnungen' },
  'BIOS': { long: 'Basic Input/Output System', category: 'IT', description: 'Firmware, startet den Computer und initialisiert Hardware' },
  'UEFI': { long: 'Unified Extensible Firmware Interface', category: 'IT', description: 'Moderner Nachfolger des BIOS' },
  'USB': { long: 'Universal Serial Bus', category: 'IT', description: 'Standardanschluss für Peripheriegeräte' },
  'HDMI': { long: 'High Definition Multimedia Interface', category: 'IT', description: 'Digitale Schnittstelle für Bild und Ton' },
  'API': { long: 'Application Programming Interface', category: 'IT', description: 'Schnittstelle zur Kommunikation zwischen Softwareanwendungen' },
  'SDK': { long: 'Software Development Kit', category: 'IT', description: 'Werkzeugsammlung zur Softwareentwicklung' },
  'IDE': { long: 'Integrated Development Environment', category: 'IT', description: 'Entwicklungsumgebung für Programmierer (z.B. VS Code)' },
  'CLI': { long: 'Command Line Interface', category: 'IT', description: 'Befehlszeilen-Schnittstelle zur Steuerung eines Computers' },
  'GUI': { long: 'Graphical User Interface', category: 'IT', description: 'Grafische Benutzeroberfläche' },
  'OS': { long: 'Operating System', category: 'IT', description: 'Betriebssystem (Windows, macOS, Linux)' },
  'SQL': { long: 'Structured Query Language', category: 'IT', description: 'Abfragesprache für relationale Datenbanken' },
  'HTML': { long: 'Hypertext Markup Language', category: 'IT', description: 'Auszeichnungssprache für Webseiten' },
  'CSS': { long: 'Cascading Style Sheets', category: 'IT', description: 'Stilvorlagesprache für das Design von Webseiten' },
  'JSON': { long: 'JavaScript Object Notation', category: 'IT', description: 'Leichtgewichtiges Datenaustauschformat' },
  'XML': { long: 'Extensible Markup Language', category: 'IT', description: 'Auszeichnungssprache zur Darstellung strukturierter Daten' },
  'OOP': { long: 'Objektorientierte Programmierung', category: 'IT', description: 'Programmierparadigma mit Klassen und Objekten' },
  'CI': { long: 'Continuous Integration', category: 'IT', description: 'Automatisierte Integration von Code-Änderungen' },
  'CD': { long: 'Continuous Deployment/Delivery', category: 'IT', description: 'Automatisierte Bereitstellung von Software' },
  'IoT': { long: 'Internet of Things', category: 'IT', description: 'Vernetzung physischer Geräte mit dem Internet' },
  'IBAN': { long: 'International Bank Account Number', category: 'Finanzen', description: 'Internationale Bankkontonummer für SEPA-Überweisungen' },
  'BIC': { long: 'Business Identifier Code', category: 'Finanzen', description: 'Eindeutiger Code zur Identifikation von Banken (auch SWIFT)' },
  '2FA': { long: 'Zwei-Faktor-Authentifizierung', category: 'IT', description: 'Zusätzliche Sicherheitsebene beim Login (z.B. SMS-Code)' },
  'MFA': { long: 'Multi-Faktor-Authentifizierung', category: 'IT', description: 'Login-Schutz mit mehreren Faktoren (Passwort + Code + Biometrie)' },
  'DDOS': { long: 'Distributed Denial of Service', category: 'IT', description: 'Cyberangriff: Überlastung von Servern durch massenhaften Traffic' },
  'VPS': { long: 'Virtual Private Server', category: 'IT', description: 'Virtueller dedizierter Server in der Cloud' },
  'SaaS': { long: 'Software as a Service', category: 'IT', description: 'Software die als Dienst über das Internet bereitgestellt wird' },
  'PaaS': { long: 'Platform as a Service', category: 'IT', description: 'Cloud-Plattform für Entwicklung und Betrieb von Anwendungen' },
  'IaaS': { long: 'Infrastructure as a Service', category: 'IT', description: 'Cloud-Infrastruktur (Server, Netzwerk) als Service' },
  'CMS': { long: 'Content Management System', category: 'IT', description: 'System zur Erstellung und Verwaltung von Web-Inhalten (z.B. WordPress)' },
  'SEO': { long: 'Search Engine Optimization', category: 'IT', description: 'Optimierung für Suchmaschinen zur Verbesserung des Rankings' },
  'SEM': { long: 'Search Engine Marketing', category: 'IT', description: 'Suchmaschinenmarketing: Bezahlte Anzeigen in Suchergebnissen' },

  // ── Medizin & Gesundheit ──────────────────────────────────────────────
  'MRT': { long: 'Magnetresonanztomographie', category: 'Medizin', description: 'Bildgebungsverfahren mit Magnetfeldern (auch MRI)' },
  'CT': { long: 'Computertomographie', category: 'Medizin', description: 'Schichtweise Röntgenaufnahme des Körpers' },
  'EKG': { long: 'Elektrokardiogramm', category: 'Medizin', description: 'Aufzeichnung der elektrischen Herzaktivität' },
  'BMI': { long: 'Body-Mass-Index', category: 'Medizin', description: 'Maßzahl für das Körpergewicht in Relation zur Körpergröße' },
  'HIV': { long: 'Humanes Immundefizienz-Virus', category: 'Medizin', description: 'Virus, der AIDS verursacht' },
  'AIDS': { long: 'Acquired Immune Deficiency Syndrome', category: 'Medizin', description: 'Durch HIV ausgelöstes Immunschwächesyndrom' },
  'PCR': { long: 'Polymerase-Kettenreaktion', category: 'Medizin', description: 'Testverfahren zur Erkennung von Erbgut (z.B. Covid-Test)' },
  'DNA': { long: 'Deoxyribonucleic Acid', category: 'Medizin', description: 'Desoxyribonukleinsäure – Träger der Erbinformation' },
  'RNA': { long: 'Ribonucleic Acid', category: 'Medizin', description: 'Ribonukleinsäure – wichtig bei Genexpression und mRNA-Impfstoffen' },
  'WHO': { long: 'World Health Organization', category: 'Medizin', description: 'Weltgesundheitsorganisation der Vereinten Nationen' },
  'RKI': { long: 'Robert Koch-Institut', category: 'Medizin', description: 'Deutsches Bundesinstitut für Infektionskrankheiten und Epidemiologie' },
  'STIKO': { long: 'Ständige Impfkommission', category: 'Medizin', description: 'Empfiehlt Impfungen in Deutschland' },
  'EBV': { long: 'Epstein-Barr-Virus', category: 'Medizin', description: 'Häufiges Herpesvirus, verursacht Pfeiffersches Drüsenfieber' },
  'ICU': { long: 'Intensive Care Unit', category: 'Medizin', description: 'Intensivstation im Krankenhaus' },
  'OP': { long: 'Operation', category: 'Medizin', description: 'Chirurgischer Eingriff' },
  'OTC': { long: 'Over the Counter', category: 'Medizin', description: 'Rezeptfreie Medikamente, erhältlich ohne Verschreibung' },
  'ADHD': { long: 'Attention Deficit Hyperactivity Disorder', category: 'Medizin', description: 'ADHS: Aufmerksamkeitsdefizit-Hyperaktivitätsstörung' },
  'ADHS': { long: 'Aufmerksamkeitsdefizit-Hyperaktivitätsstörung', category: 'Medizin', description: 'Entwicklungsstörung mit Unaufmerksamkeit und Impulsivität' },
  'CVD': { long: 'Cardiovascular Disease', category: 'Medizin', description: 'Herz-Kreislauf-Erkrankung' },
  'CPR': { long: 'Cardiopulmonary Resuscitation', category: 'Medizin', description: 'Herz-Lungen-Wiederbelebung (HLW)' },

  // ── Wirtschaft & Finanzen ─────────────────────────────────────────────
  'DAX': { long: 'Deutscher Aktienindex', category: 'Finanzen', description: 'Wichtigster Aktienindex Deutschlands mit 40 Unternehmen' },
  'ETF': { long: 'Exchange Traded Fund', category: 'Finanzen', description: 'Börsengehandelter Indexfonds – kostengünstiger Weg zu investieren' },
  'GmbH': { long: 'Gesellschaft mit beschränkter Haftung', category: 'Wirtschaft', description: 'Häufigste Unternehmensform in Deutschland' },
  'AG': { long: 'Aktiengesellschaft', category: 'Wirtschaft', description: 'Kapitalgesellschaft mit Aktien an der Börse' },
  'KG': { long: 'Kommanditgesellschaft', category: 'Wirtschaft', description: 'Personengesellschaft mit beschränkt haftenden Kommanditisten' },
  'OHG': { long: 'Offene Handelsgesellschaft', category: 'Wirtschaft', description: 'Personengesellschaft, alle Gesellschafter haften unbeschränkt' },
  'UG': { long: 'Unternehmergesellschaft', category: 'Wirtschaft', description: 'Mini-GmbH mit geringem Stammkapital (haftungsbeschränkt)' },
  'SE': { long: 'Societas Europaea', category: 'Wirtschaft', description: 'Europäische Aktiengesellschaft, in allen EU-Ländern aktiv' },
  'UVP': { long: 'Unverbindliche Preisempfehlung', category: 'Wirtschaft', description: 'Empfehlungspreis des Herstellers, nicht bindend' },
  'MwSt': { long: 'Mehrwertsteuer', category: 'Finanzen', description: 'Verbrauchsteuer auf Waren und Dienstleistungen (19% / 7%)' },
  'USt': { long: 'Umsatzsteuer', category: 'Finanzen', description: 'Entspricht der Mehrwertsteuer aus Unternehmenssicht' },
  'AfA': { long: 'Absetzung für Abnutzung', category: 'Finanzen', description: 'Steuerliche Abschreibung von Wirtschaftsgütern' },
  'ROI': { long: 'Return on Investment', category: 'Finanzen', description: 'Kennzahl für die Rentabilität einer Investition' },
  'BIP': { long: 'Bruttoinlandsprodukt', category: 'Wirtschaft', description: 'Gesamtwert aller produzierten Güter und Dienstleistungen' },
  'EZB': { long: 'Europäische Zentralbank', category: 'Wirtschaft', description: 'Zentralbank der Eurozone, legt den Leitzins fest' },
  'KMU': { long: 'Kleine und mittlere Unternehmen', category: 'Wirtschaft', description: 'Mittelstand: Unternehmen mit bis zu 249 Mitarbeitern' },
  'B2B': { long: 'Business to Business', category: 'Wirtschaft', description: 'Geschäftsbeziehungen zwischen Unternehmen' },
  'B2C': { long: 'Business to Consumer', category: 'Wirtschaft', description: 'Geschäftsbeziehungen zwischen Unternehmen und Endkunden' },
  'SEPA': { long: 'Single Euro Payments Area', category: 'Finanzen', description: 'Einheitlicher Euro-Zahlungsverkehrsraum in Europa' },
  'IPO': { long: 'Initial Public Offering', category: 'Finanzen', description: 'Börsengang: Erstmaliger Verkauf von Aktien an die Öffentlichkeit' },
  'P&L': { long: 'Profit and Loss', category: 'Finanzen', description: 'Gewinn- und Verlustrechnung' },
  'CFO': { long: 'Chief Financial Officer', category: 'Wirtschaft', description: 'Finanzvorstand eines Unternehmens' },
  'CEO': { long: 'Chief Executive Officer', category: 'Wirtschaft', description: 'Vorstandsvorsitzender / Geschäftsführer' },
  'CTO': { long: 'Chief Technology Officer', category: 'Wirtschaft', description: 'Technischer Vorstand / Leiter der Technologieentwicklung' },
  'COO': { long: 'Chief Operating Officer', category: 'Wirtschaft', description: 'Betrieblicher Vorstand, verantwortet das operative Geschäft' },
  'HR': { long: 'Human Resources', category: 'Wirtschaft', description: 'Personalmanagement und -verwaltung' },
  'PR': { long: 'Public Relations', category: 'Wirtschaft', description: 'Öffentlichkeitsarbeit und Kommunikation nach außen' },
  'KPI': { long: 'Key Performance Indicator', category: 'Wirtschaft', description: 'Leistungskennzahl zur Messung des Unternehmenserfolgs' },
  'USP': { long: 'Unique Selling Proposition', category: 'Wirtschaft', description: 'Alleinstellungsmerkmal eines Produkts oder Unternehmens' },

  // ── EU & Politik ──────────────────────────────────────────────────────
  'EU': { long: 'Europäische Union', category: 'Politik', description: 'Staatenbund aus 27 europäischen Ländern' },
  'EWG': { long: 'Europäische Wirtschaftsgemeinschaft', category: 'Politik', description: 'Vorläufer der EU, gegründet 1957' },
  'NATO': { long: 'North Atlantic Treaty Organization', category: 'Politik', description: 'Nordatlantisches Verteidigungsbündnis' },
  'UN': { long: 'United Nations', category: 'Politik', description: 'Vereinte Nationen – internationales Forum für Frieden und Sicherheit' },
  'UNO': { long: 'United Nations Organization', category: 'Politik', description: 'Vereinte Nationen (Deutsche Bezeichnung)' },
  'SPD': { long: 'Sozialdemokratische Partei Deutschlands', category: 'Politik', description: 'Sozialdemokratische Partei, gegründet 1863' },
  'CDU': { long: 'Christlich Demokratische Union', category: 'Politik', description: 'Christlich-konservative Partei in Deutschland' },
  'CSU': { long: 'Christlich-Soziale Union', category: 'Politik', description: 'Bayerische Schwesterpartei der CDU' },
  'FDP': { long: 'Freie Demokratische Partei', category: 'Politik', description: 'Liberale Partei in Deutschland' },
  'AFD': { long: 'Alternative für Deutschland', category: 'Politik', description: 'Rechtspopulistische Partei, gegründet 2013' },
  'BSW': { long: 'Bündnis Sahra Wagenknecht', category: 'Politik', description: 'Linkskonservative Partei, gegründet 2024' },
  'DSGVO': { long: 'Datenschutz-Grundverordnung', category: 'EU', description: 'EU-Verordnung zum Schutz personenbezogener Daten (seit 2018)' },
  'GDPR': { long: 'General Data Protection Regulation', category: 'EU', description: 'Englische Bezeichnung für die DSGVO' },
  'AI Act': { long: 'Artificial Intelligence Act', category: 'EU', description: 'EU-Gesetz zur Regulierung von KI-Systemen (2024)' },
  'DSA': { long: 'Digital Services Act', category: 'EU', description: 'EU-Gesetz für digitale Dienste und Plattformregulierung' },
  'DMA': { long: 'Digital Markets Act', category: 'EU', description: 'EU-Gesetz gegen marktbeherrschende Gatekeeper (Google, Meta, etc.)' },
  'BEU': { long: 'Bundesrat der Europäischen Union', category: 'EU', description: 'Rat, in dem die EU-Mitgliedstaaten vertreten sind' },
  'EP': { long: 'Europäisches Parlament', category: 'EU', description: 'Direkt gewähltes Parlament der Europäischen Union' },

  // ── Alltag & Kommunikation ────────────────────────────────────────────
  'MfG': { long: 'Mit freundlichen Grüßen', category: 'Alltag', description: 'Standard-Briefabschluss in formellen E-Mails und Briefen' },
  'LG': { long: 'Liebe Grüße', category: 'Alltag', description: 'Informeller Briefabschluss unter Freunden' },
  'VG': { long: 'Viele Grüße', category: 'Alltag', description: 'Semi-formeller Briefabschluss' },
  'BzW': { long: 'Beziehungsweise', category: 'Alltag', description: 'Grammatikalische Verbindung für Alternativen' },
  'DH': { long: 'Das heißt', category: 'Alltag', description: 'Erklärende Verbindung (lat.: id est, i.e.)' },
  'ZB': { long: 'Zum Beispiel', category: 'Alltag', description: 'Einleitung eines Beispiels (lat.: exempli gratia, e.g.)' },
  'USW': { long: 'Und so weiter', category: 'Alltag', description: 'Fortsetzung einer Aufzählung (etc.)' },
  'UAM': { long: 'Und andere mehr', category: 'Alltag', description: 'Wie et alii (et al.) in Wissenschaftstexten' },
  'INKL': { long: 'Inklusive', category: 'Alltag', description: 'Einschließlich, mit inbegriffen' },
  'ZZGL': { long: 'Zuzüglich', category: 'Alltag', description: 'Zuzüglich einer Summe (plus)' },
  'ABZGL': { long: 'Abzüglich', category: 'Alltag', description: 'Abzüglich einer Summe (minus)' },
  'EVTL': { long: 'Eventuell', category: 'Alltag', description: 'Möglicherweise, vielleicht' },
  'ASAP': { long: 'As soon as possible', category: 'Alltag', description: 'So schnell wie möglich' },
  'FYI': { long: 'For your information', category: 'Alltag', description: 'Zu deiner Information' },
  'TLDR': { long: 'Too long; didn\'t read', category: 'Alltag', description: 'Zusammenfassung eines langen Textes' },
  'AKA': { long: 'Also known as', category: 'Alltag', description: 'Auch bekannt als' },
  'IMO': { long: 'In my opinion', category: 'Alltag', description: 'Meiner Meinung nach' },
  'IMHO': { long: 'In my humble opinion', category: 'Alltag', description: 'Meiner bescheidenen Meinung nach' },
  'LOL': { long: 'Laughing out loud', category: 'Alltag', description: 'Laut lachen – Internet-Ausdruck für etwas Lustiges' },
  'OMG': { long: 'Oh my God', category: 'Alltag', description: 'Ausdruck der Überraschung oder des Entsetzens' },
  'BTW': { long: 'By the way', category: 'Alltag', description: 'Übrigens / nebenbei' },
  'IRL': { long: 'In real life', category: 'Alltag', description: 'Im echten Leben (nicht online)' },
  'DM': { long: 'Direct Message', category: 'Alltag', description: 'Persönliche Nachricht in sozialen Netzwerken' },

  // ── Zeit & Einheiten ──────────────────────────────────────────────────
  'MEZ': { long: 'Mitteleuropäische Zeit', category: 'Zeit', description: 'Standardzeit in Deutschland (UTC+1)' },
  'MESZ': { long: 'Mitteleuropäische Sommerzeit', category: 'Zeit', description: 'Sommerzeit in Deutschland (UTC+2)' },
  'UTC': { long: 'Coordinated Universal Time', category: 'Zeit', description: 'Koordinierte Weltzeit als Referenzzeitzone' },
  'GMT': { long: 'Greenwich Mean Time', category: 'Zeit', description: 'Mittlere Greenwich-Zeit, Basis für Zeitzonen' },
  'KWh': { long: 'Kilowattstunde', category: 'Einheiten', description: 'Energieeinheit: 1.000 Wattstunden Strom oder Wärme' },
  'PS': { long: 'Pferdestärke', category: 'Einheiten', description: 'Veraltete Leistungseinheit für Motoren (≈ 0,735 kW)' },
  'KW': { long: 'Kilowatt', category: 'Einheiten', description: 'Moderne Leistungseinheit (1 kW = 1,36 PS)' },
  'KMH': { long: 'Kilometer pro Stunde', category: 'Einheiten', description: 'Geschwindigkeitseinheit im Straßenverkehr' },

  // ── Gaming & Internet-Kultur ──────────────────────────────────────────
  'NPC': { long: 'Non-Player Character', category: 'Gaming', description: 'Vom Computer gesteuerter Charakter in einem Spiel' },
  'FPS': { long: 'Frames per Second', category: 'Gaming', description: 'Bilder pro Sekunde – Maß für Flüssigkeit in Spielen' },
  'RPG': { long: 'Role-Playing Game', category: 'Gaming', description: 'Rollenspiel: Spieler schlüpft in eine Figur' },
  'AFK': { long: 'Away from Keyboard', category: 'Gaming', description: 'Abwesend vom Tastatur / Computer' },
  'GG': { long: 'Good Game', category: 'Gaming', description: 'Respektvolle Geste am Spielende' },
  'GG EZ': { long: 'Good Game Easy', category: 'Gaming', description: 'Oft als Provokation: Spiel war leicht' },
  'OP': { long: 'Overpowered', category: 'Gaming', description: 'Zu stark, zu mächtig (auch: Original Poster im Forum)' },
  'MMO': { long: 'Massively Multiplayer Online', category: 'Gaming', description: 'Onlinespiel mit sehr vielen gleichzeitigen Spielern' },
  'MMORPG': { long: 'Massively Multiplayer Online Role-Playing Game', category: 'Gaming', description: 'Massives Mehrspieler-Online-Rollenspiel' },
  'DLC': { long: 'Downloadable Content', category: 'Gaming', description: 'Herunterladbarer Zusatzinhalt für Videospiele' },
  'PVP': { long: 'Player vs. Player', category: 'Gaming', description: 'Spielmodus: Spieler kämpfen gegeneinander' },
  'PVE': { long: 'Player vs. Environment', category: 'Gaming', description: 'Spielmodus: Spieler gegen KI-Gegner' },
  'UI': { long: 'User Interface', category: 'IT', description: 'Benutzeroberfläche einer Anwendung oder Webseite' },
  'UX': { long: 'User Experience', category: 'IT', description: 'Gesamterlebnis des Nutzers beim Verwenden einer Software' },
  'FAQ': { long: 'Frequently Asked Questions', category: 'Alltag', description: 'Häufig gestellte Fragen und deren Antworten' },

  // ── Stellenanzeigen & Beruf ────────────────────────────────────────────
  'VZ': { long: 'Vollzeit', category: 'Beruf', description: 'Vollzeitbeschäftigung (z.B. 38–40 Stunden/Woche)' },
  'TZ': { long: 'Teilzeit', category: 'Beruf', description: 'Teilzeitbeschäftigung mit reduzierter Stundenzahl' },
  'BW': { long: 'Bewerbung', category: 'Beruf', description: 'Unterlagen zur Bewerbung um eine Stelle' },
  'CV': { long: 'Curriculum Vitae', category: 'Beruf', description: 'Lebenslauf (englische Bezeichnung)' },
  'HR': { long: 'Human Resources', category: 'Beruf', description: 'Personalabteilung eines Unternehmens' },
  'PKW': { long: 'Personenkraftwagen', category: 'Beruf', description: 'Privater Pkw (oft: Führerschein Klasse B notwendig)' },
  'BMAS': { long: 'Bundesministerium für Arbeit und Soziales', category: 'Beruf', description: 'Zuständig für Arbeitsrecht und Sozialpolitik' },
  'HO': { long: 'Home Office', category: 'Beruf', description: 'Arbeit von zuhause aus' },
  'WFH': { long: 'Work from Home', category: 'Beruf', description: 'Englisch für Home Office' },
  'KPI': { long: 'Key Performance Indicator', category: 'Beruf', description: 'Leistungskennzahl zur Beurteilung der Mitarbeitenden' },
  'OKR': { long: 'Objectives and Key Results', category: 'Beruf', description: 'Zielsetzungsframework (Google, Intel)' },
  'PM': { long: 'Project Manager / Product Manager', category: 'Beruf', description: 'Projektleiter oder Produktmanager' },

};

module.exports = acronyms_data;
